"""first migrate

Revision ID: 783c4cdd856f
Revises: 
Create Date: 2022-01-25 12:32:22.846598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783c4cdd856f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'email',
               existing_type=sa.VARCHAR(length=75), nullable=False)
    op.alter_column('student', 'profile_picture',
               existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column('student', 'joined_on',
               existing_type=sa.DATETIME(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'joined_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('student', 'profile_picture',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('student', 'email',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    # ### end Alembic commands ###
